### ISSUE TITLE
Dependancies in index.html.ejs

### ISSUE THREAD

**Issue by GazzaHazza** [vikpe/react-webpack-babel-starter#3]
Hi, Thanks for the starter repo. Time saver as didnt want to use create-react-app.

This is more of a question really than an issue, just curious to why you have -
```
        <!-- Dependencies -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.1.1/umd/react.production.min.js" integrity="sha256-aOOjVC95SZguoWsCaRskLhkbVFsaYKoYJom4VdHlOEo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.1.1/umd/react-dom.production.min.js" integrity="sha256-d0hfGFA209oNZEnEJ8ZJKLl9+ZMFeIrIAiFzaSSRY5U=" crossorigin="anonymous"></script>
```
In the `index.html.ejs` file as well as `react` & `reactDOM` in `devDependancies`? Why not add it into the `dependancies` section of `package.json` as surely wont need to bump version in two places with each release of the packages?

**Comment by vikpe** [comment]
@GazzaHazza I've chosen to include the React/ReactDOM libs from a CDN instead of including them in the build.

This reduces build time during development and load time for users as there is a high chance that they already have React/ReactDOM in their browser cache.

In webpack termonology it's called [externals](https://webpack.js.org/configuration/externals/) and is defined in the webpack config.

> The externals configuration option provides a way of excluding dependencies from the output bundles. Instead, the created bundle relies on that dependency to be present in the consumer's environment. 

In this repo I've configured it in [`/configs/webpack/common.js`](https://github.com/vikpe/react-webpack-babel-starter/blob/4fc23e7c11e55bca4c7220e904051951fea2a047/configs/webpack/common.js#L48):
```javascript
 externals: {
    'react': 'React',
    'react-dom': 'ReactDOM',
  },
```
